### ISSUE TITLE
Not able to close window when stop mirroring in Linux.

### ISSUE THREAD

**Issue by malikAr** [antimof/UxPlay#95]
I need help in, how to implement the closing of windows when we stop any mirroring. Currently, when we close the mirroring its window remains open.

I need a window created on start and a window close on stop.

**Comment by malikAr** [comment]
@fduncanh @antimof  Please help

**Comment by fduncanh** [comment]
Since uxplay 1.45,  the mirror window should close when you stop mirroring (unless you use the -nc option) , except in macOS.   

are you using macOS?
are you using a recent uxplay?



if you are talking about the terminal window, you can close it with ctrl-C.  

describe your system.  Linux distrbution , macOS,     Desktop, Raspberry Pi, etc.?

**Comment by malikAr** [comment]
I have ubuntu 18.04 and currently using UXPlay 1.45.
But still mirroring window(Video render window) open when mirroring stop and on a new connection new window opens.

**Comment by fduncanh** [comment]
Please upgrade to a later uxplay.    The latest is at http://github.com/FDH2/UxPlay  (1.55) as are older releases.
 but 1.54 is available on this antimof site.

**Comment by malikAr** [comment]
Hi @fduncanh , I have upgrade to 1.55 , but still facing same problem . First Video window is not closed on stop mirroring from iPhone 7(15.4), when we give next connection new window open with old window still open.

One more thing how to run two device mirroring at same time e.g two iPhone or one iPhone and one mac.

**Comment by fduncanh** [comment]
It works fine for me on Ubuntu 20.04    (Ubuntu 18.04 is too old so I no longer have a test setup for that, you probably  should upgrade to Ubuntu 22.04  note 22.04 uses wayland graphics by default I think)

I have no idea what your problem is due to.  What does "uxplay -v" report?  Perhaps you are actually running an older version of uxplay  because the new one is not correctly installed?

for 1.55 uxplay -v should report:
UxPlay version 1.55; for help, use option "-h"



To mirror two devices at the same time you need two running instances of uxplay.

The second one needs a different name, mac address and network ports

use (for the second instance)
uxplay -m -n  uxplay2 -p 35000

to use a random mac address (-m), name "uxplay2" and  UDP+TCP ports 35000, 35001, 35002 (these have to be open if you use a firewall),

**Comment by malikAr** [comment]
@fduncanh , Yes I am getting same "UxPlay version 1.55; for help, use option "-h"" when run uxplay -v. But still facing same issue.

**Comment by fduncanh** [comment]
Maybe  the default option "-vs autovideosink" is choosing   a partially-broken "videosink" for rendering video on your system,
that is not closing the widow  properly.  This has sometime happened with glimagesink.

Try these options one by one to see if one or more of the fixes things

-avdec 

-vs ximagesink

-vs xvimagesink

-vs glimagesink

-vs gtksink

**Comment by malikAr** [comment]
@fduncanh Yes 1st option is working . Thanks

**Comment by fduncanh** [comment]
uninstalling gstreamer1.0-vaapi should be the best way to fix your issue, I think.
